### ISSUE TITLE
To Future Self: Fix the hardcoded channel values

### ISSUE THREAD

**Issue by LRTNZ** [Simpit-team/KerbalSimpitRevamped#11]
With the current system, the event channel firing things relies on hardcoded string values in the mod - which is really not a nice way to do things. To improve things, the best approach will be to either redo that part of the system entirely, to make use of enums or something, or alternatively generate those string values with the values in the enum at run/compile time.

**Comment by PBechon** [comment]
@LRTNZ Do you want me to do the rewrite using the same logic that the one I used on Timewarp or do you have something else in mind ?

For reference, here is how I did it to avoid the hardcoded values

`WarpChannel = GameEvents.FindEvent<EventData<byte, object>>("onSerialReceived" + InboundPackets.WarpChange);`

**Comment by LRTNZ** [comment]
I did have something else in mind - I will look into it some more, to see how I best feel this system can be expanded without breaking things to much.

**Comment by PBechon** [comment]
Fixed in commit 85488ad2d1e6048990daa087a28f2a067cee92d6
