### ISSUE TITLE
[Feature]: Stage Information

### ISSUE THREAD

**Issue by CdRGit** [Simpit-team/KerbalSimpitRevamped#68]
## Is your feature request related to a problem? Please describe.
Can't currently display stage information using SimPit

### A clear and concise description of what the problem is. Ex. I'm always frustrated when [...]
Currently SimPit offers no way of getting the stage number

### What is the issue that you are facing, that you would like resolved? How would it benefit players?
Adding a stage information package would allow controllers to display this information, allowing for better immersion

### Is it an existing/new feature in the game that would benefit from support by this mod?
Existing, staging indicator

### A clear and concise description of what you want to happen.
Implementation of a packet which contains current stage number and (if possible) total stage count

### How would it be best that the feature is implemented? What sort of data may need to be sent by the mod to controllers? Would it require a digital signal, or an analogue one? Maybe it needs a terminal command to help use it, or a GUI button?
The mod needs to send a packet containing some numbers (bytes would probably be big enough for most cases, but the in game display goes up to three digits so short could be considered as well)

### 

## Describe alternatives you've considered
Looked through docs to see if this was already possible, couldn't find anything

### A clear and concise description of any alternative solutions or features you've considered.
-

### What about the current features of the program do not quite, if at all, allow you to implement/carry out what you would like to do? 
There is to my knowledge no way to get current stage number and total stage count as of now

### What is the nearest feature in the mod (If there is one), that is along the lines of what you are suggesting?
Probably flight status

## Additional context
-

### Add any other context or screenshots about the feature request here. Any drawings, screenshots, pseudocode/logic diagrams, and more are all appreciated. Anything that you feel may help others understand your idea would be great!
-

**Comment by PBechon** [comment]
Added with 50b8f7db99201fa927f2764b07690db502220502
