### ISSUE TITLE
[Feature]: get a readback from the throttle position from KSP

### ISSUE THREAD

**Issue by MVermeij** [Simpit-team/KerbalSimpitRevamped#79]
## Is your feature request related to a problem? Please describe.
I would like to have the possibility to get a readback  the throttle from KSP (similar to for example getting the current altitude). The reason is that I have a motorized slider, for throttle control and I would like it to follow throttle changes if I use Mechjeb2 for controlling the spacecraft. 

### What is the nearest feature in the mod (If there is one), that is along the lines of what you are suggesting?
A solution similar to the readback from the current altitude (or any other parameter for that matter).

## Additional context
As discussed on Discord, this feature is indeed not already present in the plugin:
rogor
 — 
31/01/2022
This is not a feature of SimPit currently
But we can investigate it, in theory it should not be that hard to add
Can you create a feature request on GitHub so that this request is not forgotten ?

I understand that this can create a feedbackloop if I do not properly seperate manual throttle movement from motorized movement because of received data from KSP. Features to help prevent this are actually already implemented in these motorized sliders in that they can detect whether they are touched or not.

**Comment by PBechon** [comment]
This is a feature requested by several people. Let's plan to have it in the next version.

We should probably send to arduino the current value of the throttle, yaw/pitch/roll, custom axis, translation, wheel throttle, wheel steering command

**Comment by bespezzano** [comment]
Just joining the request, I will only use throttle though. Thanks!

**Comment by PBechon** [comment]
This has been added with commit c5ba9354d963e32309a59ea14aeed8a6b3fdabc1
