### ISSUE TITLE
[Feature]: Add G Forces data outbound messages

### ISSUE THREAD

**Issue by c0untzer0** [Simpit-team/KerbalSimpitRevamped#80]
## Is your feature request related to a problem? Please describe.
<br>

### I would like to monitor G forces on my controller (eventually maybe have a dedicated display for it).

<br>

### I would like to be able to subscribe to a GFORCE_MESSAGE channel, or have G Force (acceleration) info sent in another existing channel (FLIGHT_STATUS_MESSAGE).

<br>

### Using existing channels seems like a good idea, the API should already publish the data, as SerialIO implements it already.

<br>

### 

## Describe alternatives you've considered
<br>

### N/A
<br>

### FLIGHT_STATUS_MESSAGE, etc, don't publish acceleration/G forces data.
<br>

### Maybe the acceleration data can be added to the FLIGHT_STATUS_MESSAGE channel. Seems like a good place for it.

<br>

## Additional context
<br>

### Add any other context or screenshots about the feature request here. Any drawings, screenshots, pseudocode/logic diagrams, and more are all appreciated. Anything that you feel may help others understand your idea would be great!

Maybe it can be added to the flightStatusMessage struct:

{
  byte flightStatusFlags; /**< Different booleans as defined by FligthStatusFlags. You can access them with the helper funtions.*/
...
  float gForces; /**< Current experienced G forces on vessel */
  byte currentStage; /**< Current stage of the vessel (also the total number of stage remaining). Decreased by one at each staging. 
...
} __attribute__((packed));

**Comment by PBechon** [comment]
Seems totally feasible (and easy) by getting the value of `ActiveVessel.geeForce`.

Not sure that it would be a good fit for the flightStatusMessage  though. To be consistent with speed messages, how about having a dedicated message for acceleration. We can have for instance in the message : 
- The acceleration (3 float, don't know what reference frame is used though ...)
- The gForce (1 float)

If the acceleration is not useful, we can have only the gForce.

**Comment by c0untzer0** [comment]
That sounds like a plan. The speed message would be a good place to put it too.
I think acceleration and Gforce could both be included to get whatever is easier without converting things.

**Comment by PBechon** [comment]
gForces has been added to the airspeed message in 85d7fcbdb74bb7649074a6c102c9ef977d1bed0e
