### ISSUE TITLE
[BUG]:

### ISSUE THREAD

**Issue by JoelFSwe** [Simpit-team/KerbalSimpitRevamped#85]
Hello there seems to be an issue with the new version of simpit 2.2.0. I am unable to complete the handshake with the new version. It is stuck at "WAITING_HANDSHAKE". It is however working just fine with version 2.1.0.

Really appreciate the work put into this. The new gForces value comes in real handy :) (if the new version would work haha)

Thank you!

**Comment by LRTNZ** [comment]
Hey there! Are you on the discord server? As feel free to ask there as it will be easier for us to help you there.

**Comment by PBechon** [comment]
The release note describe this case : you also need to use the latest Arduino lib since we changed the underlying protocol. Can you triple check that you are using also the v2.2 Arduino version ?

If this is the case, can you share the KSP log file ? Any error that appear when trying to connect ?

**Comment by JoelFSwe** [comment]
> LRTNZ

I have discord. No what is the discord server called?

> PBechon

The library i am using is called: KerbalSimpitRevamped-Arduino-2.2.0
The thing is gForces does not exist in 2.1.0 so it won't allow me to upload my code with that library. With 2.2.0 i can upload with gForces but it wont complete the handshake. In the KSP log it only says waiting for handshake, no error is displayed.

Thanks!

**Comment by JoelFSwe** [comment]
> LRTNZ

I have discord. No what is the discord server called?

>   PBechon

The library i am using is called: KerbalSimpitRevamped-Arduino-2.2.0
The thing is gForces does not exist in 2.1.0 so it won't allow me to upload my code with that library. With 2.2.0 i can upload with gForces but it wont complete the handshake. In the KSP log it only says waiting for handshake, no error is displayed.

Thanks!

**Comment by PBechon** [comment]
The discord link is on the front page : https://discord.gg/ZwcPdNcaRN

Can you set the verbose mode to true (in the SimPit config file), and see if there is any error log that appears ?

**Comment by JoelFSwe** [comment]
I always feel so dumb when i find the problem, i didn't update the gamedata files to 2.2.0

But thanks i might need to discord later :)

**Comment by PBechon** [comment]
You had me in the beginning, I thought we let a big issue as this one slip into the release. Feel free to join the discord anytime.

I'm closing the issue since this is now resolved
