### ISSUE TITLE
[Feature]: setting to invert pitch axis

### ISSUE THREAD

**Issue by fommil** [Simpit-team/KerbalSimpitRevamped#97]
## Is your feature request related to a problem?

I have one of the fantastic https://untitledspacecraft.com/ analog controls but I prefer to invert the pitch axis of my rocket controls so that the navball moves consistently in both directions.

Unfortunately there is no button on the controller to invert the pitch axis, and the kerbal Input settings (for primary and secondary controls) don't seem to affect the input that is coming in from simpit (although please correct me if I'm wrong and have overlooked something!).

Of course I could go rewiring the hardware or edit the firmware to change what is sent, but that all seems a bit overkill since Kerbal wouldn't expect one to do this with a regular flight controller.

## Describe the solution you'd like

Operating on the assumption that there is no existing way to invert the pitch axis, I would like the simpit mod to be able to perform the inversion. By default, it could behave exactly as it currently does, but I believe this method is `AxisControl.cs`

```cs
        public void vesselRotationCallback(byte ID, object Data)
        {
            newRotation = KerbalSimpitUtils.ByteArrayToStructure<RotationalStruct>((byte[])Data);
            // Bit fields:
            // pitch = 1
            // roll = 2
            // yaw = 4
            if ((newRotation.mask & (byte)1) > 0)
            {
                myRotation.pitch = newRotation.pitch;
            }
            if ((newRotation.mask & (byte)2) > 0)
            {
                myRotation.roll = newRotation.roll;
            }
            if ((newRotation.mask & (byte)4) > 0)
            {
                myRotation.yaw = newRotation.yaw;
            }
        }
```

could be modified so that the line

```
                myRotation.pitch = newRotation.pitch;
```

is inverted if a boolean setting has been set to true. I assume that "invert" here would mean flipping the sign? Or does it require rotating about some fixed point, perhaps `2^15 - pitch`?

The setting could then be exposed as an optional parameter in the settings, perhaps on `SerialPort` so that multiple devices can be configured separately.

This should not impact the translational Y axis (that would require its own setting), and ideally there would be a separate setting for when the controller is in PLN (plane) vs RKT (rocket) modes since some people might actually want to invert the axis only when in space but have more traditional "pull back to go up" behaviour when flying a plane. I don't know which parameter to look at to get that information, but it would certainly just be a "nice to have".

I'd be happy to raise a Pull Request but I don't have a modern c# dev environment (I have a virtualbox pinned to a very old version of Visual Studio 2017 Community Edition for another open source project running .net 4.7 and c# lang version 7.0) so that might be a problem. UPDATE: I actually tried to compile the project and it failed, but I could try using Mono on Linux... although I note that the BUILDING docs say this path is out of date.

// @CodapopKSP

**Comment by rettoph** [comment]
Personally I'm not sure I like the direction this change would push the mod. I believe the controller should be responsible for any data manipulation before sending raw data to KSP. The KSP side should blindly "accept" incoming data and shouldn't mutate the data in anyway before applying it. 

Making the KSP mod something of a black box could cause confusion down the line, and keeping a clear separation of concerns helps alleviate that.

---

I know @CodapopKSP has been working to make his controller code much easier to customize and update. It should be trivial to implement the desired inversion if theres not already a simple way to do so. I could probably help you through that process if you'd like @fommil 

---

Side note: im not an official maintainer or anything. Just giving my opinion on the feature in general

**Comment by fommil** [comment]
thanks for the insight on that @rettoph ... I have edited the firmware of the controller to do what I want so I'm happy with that approach 😄

for anybody who wants to do the same as me, I edited the `readAnalog` subroutine to have a conditional on the vehicle type... around line 84 in version 2.3 of the hub software (which I don't believe is open source at present)

```
  if (vehicleType == rocket) {
    Analog_axis1 = convertAnalog_flipped(raxis2);
  } else {
    Analog_axis1 = convertAnalog(raxis2);
  }
```

(and I didn't even forget to update my throttle values in `settings.h`, honest 😄 )

**Comment by fommil** [comment]
https://github.com/CodapopKSP/UntitledSpaceCraft/pull/1
